name: Run E2E tests
description: "Run the E2E tests against an environment"

inputs:
  ENV:
    description: "The project_ENV file to use."
    required: true

runs:
  using: composite
  steps:
    - name: Test with Chromedriver
      working-directory: .
      env:
        ENV: ${{ inputs.ENV }}
        PLATFORM: ${{ inputs.PLATFORM }}
        APPCENTER_ACCESS_TOKEN: ${{ inputs.APPCENTER_ACCESS_TOKEN }}
        APPCENTER_NAME: ${{ inputs.APPCENTER_NAME }}
        APPCENTER_ENVIRONMENT: ${{ inputs.APPCENTER_ENVIRONMENT }}
        CODE_PUSH_NAME: ${{ inputs.CODE_PUSH_NAME }}

      run: |
        name=`echo $GITHUB_REPOSITORY | sed -e 's/.*\///'`
        alias=`echo "$name-$GITHUB_HEAD_REF" | tr '_' '-' | tr '/' '-'`
        ./../mobile/.bin/distribute-mobile.sh $APPCENTER_NAME $APPCENTER_ENVIRONMENT $alias $PLATFORM $CODE_PUSH_NAME

      shell: bash
