name: Run E2E tests
description: "Run the E2E tests against an environment"

inputs:
  ENV:
    description: "The project_ENV file to use."
    required: true
  PLATFORM:
    description: "ios | android - determines what gets deployed"
    required: true
  APPCENTER_ACCESS_TOKEN:
    description: "Needed to communicate with AppCenter"
    required: true
  APPCENTER_NAME:
    description: "The AppCenter Project name to do native builds"
    required: true
  CODE_PUSH_ENVIRONMENT:
    description: "Production|Staging for Code Push Builds"
    required: true
  CODE_PUSH_NAME:
    description: "The AppCenter Project name to do Code Push Builds"
    required: true
  APPCENTER_NAME_ANDROID_PRODUCTION:
    description: "Used in clone-config"
    required: true
  APPCENTER_NAME_IOS_PRODUCTION:
    description: "Used in clone-config"
    required: true

runs:
  using: composite
  steps:
    - name: Test with Chromedriver
      working-directory: mobile
      env:
        ENV: ${{ inputs.ENV }}
        PLATFORM: ${{ inputs.PLATFORM }}
        APPCENTER_ACCESS_TOKEN: ${{ inputs.APPCENTER_ACCESS_TOKEN }}
        APPCENTER_NAME: ${{ inputs.APPCENTER_NAME }}
        CODE_PUSH_ENVIRONMENT: ${{ inputs.CODE_PUSH_ENVIRONMENT }}
        CODE_PUSH_NAME: ${{ inputs.CODE_PUSH_NAME }}
        CI_COMMIT_REF_NAME: $CI_COMMIT_REF_NAME
        APPCENTER_NAME_ANDROID_PRODUCTION: ${{ inputs.APPCENTER_NAME_ANDROID_PRODUCTION }}
        APPCENTER_NAME_IOS_PRODUCTION: ${{ inputs.APPCENTER_NAME_IOS_PRODUCTION }}

      run: |
        chmod +x ./../mobile/.bin/distribute-mobile.sh
        name=`echo $GITHUB_REPOSITORY | sed -e 's/.*\///'`
        CI_COMMIT_REF_NAME=$GITHUB_REF_NAME
        npm i
        ./../mobile/.bin/distribute-mobile.sh $APPCENTER_NAME $CODE_PUSH_ENVIRONMENT $GITHUB_REF_NAME $PLATFORM $CODE_PUSH_NAME

      shell: bash
