# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ssgboilerplate' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for trainmate

#crashlytics	pod 'Fabric'
#crashlytics	pod 'Crashlytics'
#charts   pod 'Charts', '3.0.1'
#charts   pod 'SwiftyJSON', '3.1.4'
    pod 'Google/SignIn'
    pod 'Branch'
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
    pod 'Firebase/Analytics'

  pod 'ReactNativeFabric', :path => '../node_modules/react-native-fabric'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
