# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'mobile' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'Analytics'
  pod 'React', :path => '../node_modules/react-native'
  pod 'SegmentAnalytics', :path => '../node_modules/react-native-segment-analytics/ios'

  target 'mobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
