
declare namespace NodeJS {
  interface Global {
    global: any;
    API: any;
    Actions: any;
    AppActions: any;
    AsyncStorage: any;
    Button: any;
    Column: any;
    Constants: any;
    E2E: any;
    ErrorMessage: any;
    FormGroup: any;
    Format: any;
    Input: any;
    InputGroup: any;
    Link: any;
    Loader: any;
    MaskedInput: any;
    Project: any;
    Row: any;
    Select: any;
    Strings: any;
    SuccessMessage: any;
    Utils: any;
    _data: any;
    _: any;
    __DEV__: any;
    __dirname: any;
    ga: any;
    mixpanel: any;
    module: any;
    openAlert: any;
    openConfirm: any;
    process: any;
    require: any;}
}

declare let global: any;
declare let API: any;
declare let Actions: any;
declare let AppActions: any;
declare let AsyncStorage: any;
declare let Button: any;
declare let Column: any;
declare let Constants: any;
declare let E2E: any;
declare let ErrorMessage: any;
declare let FormGroup: any;
declare let Format: any;
declare let Input: any;
declare let InputGroup: any;
declare let Link: any;
declare let Loader: any;
declare let MaskedInput: any;
declare let Project: any;
declare let Row: any;
declare let Select: any;
declare let Strings: any;
declare let SuccessMessage: any;
declare let Utils: any;
declare let _: any;
declare let __DEV__: any;
declare let __dirname: any;
declare let ga: any;
declare let mixpanel: any;
declare let module: any;
declare let openAlert: any;
declare let openConfirm: any;
declare let process: any;
declare let require: any;
