name: Run E2E tests
description: "Run the E2E tests against an environment"

inputs:
  ENV:
    description: "The project_ENV file to use."
    required: true

runs:
  using: composite

  steps:
    - name: Deploy to Branch
      working-directory: .
      env:
        ENV: ${{ inputs.ENV }}
        NOW_TOKEN: ${{ secrets.NOW_TOKEN }}
        NOW_TEAM_NAME: ${{ secrets.NOW_TEAM_NAME }}

      run: |
        name=`echo $GITHUB_REPOSITORY | sed -e 's/.*\///'`
        url=$(npx vercel --token $NOW_TOKEN --scope $NOW_TEAM_NAME --confirm --build-env ENV=$ENV --name=$name
        npx vercel alias --token $NOW_TOKEN --scope $NOW_TEAM_NAME $url $name-$GITHUB_REF_NAME
      shell: bash
