name: Run E2E tests
description: "Run the E2E tests against an environment"

inputs:
  ENV:
    description: "The project_ENV file to use."
    required: true

runs:
  using: composite

  steps:
    - name: Deploy to Production
      working-directory: .
      run: |
        - repo=$GITHUB_REPOSITORY | sed -e 's/.*\///'
        - npx vercel --prod --token ${{ secrets.NOW_TOKEN }} --scope ${{ secrets.NOW_TEAM_NAME }} --confirm --build-env ENV=${{ inpits.ENV }} --name=$repo
      shell: bash
