name: Run E2E tests
description: "Run the E2E tests against an environment"

inputs:
  ENV:
    description: "The project_ENV file to use."
    required: true

runs:
  using: composite

  steps:
    - name: Deploy to Production
      working-directory: .
      env:
        ENV: ${{ inputs.ENV }}
        NOW_TOKEN: ${{ secrets.NOW_TOKEN }}
        NOW_TEAM_NAME: ${{ secrets.NOW_TEAM_NAME }}
        REPO: $GITHUB_REPOSITORY | sed -e 's/.*\///'
      run: |
        - npx vercel --prod --token $NOW_TOKEN --scope $NOW_TEAM_NAME  --confirm --build-env ENV=$ENV --name=$REPO
      shell: bash
