name: Frontend Deploy to Production

on:
  push:
    branches:
      - main
    paths:
      - ".github/**/*"
      - "*"
      - "common/**/*"
      - "components/**/*"
      - "pages/**/*"
      - "project/**/*"
      - "static/**/*"
      - "patches/**/*"
      - "public/**/*"
      - "styles/**/*"
      - "tests/**/*"

defaults:
  run:
    working-directory: .

jobs:
  web-production:
    runs-on: ubuntu-latest
    name: Web Production
    environment: production

    steps:
      - name: Cloning repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Web Cache
        uses: ./.github/actions/web-cache-action
      - name: Web Deploy Production
        uses: ./.github/actions/web-deploy-prod-action
        with:
          ENV: prod
          NOW_TOKEN: ${{ secrets.NOW_TOKEN }}
          NOW_TEAM_NAME: ${{ secrets.NOW_TEAM_NAME }}
