name: Frontend Deploy to Production

on:
  push:
    branches:
      - main
    paths:
      - ".github"
      - "*"
      - "common/**/*"
      - "components/**/*"
      - "pages/**/*"
      - "project/**/*"
      - "static/**/*"
      - "patches/**/*"
      - "public/**/*"
      - "styles/**/*"
      - "tests/**/*"

defaults:
  run:
    working-directory: .

jobs:
  web-production:
    runs-on: ubuntu-latest
    name: Web Production
    environment: production

    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Web Cache
        uses: ./.github/actions/web-cache
      - name: Run E2E tests against local
        uses: ./.github/actions/web-test-action
        with:
          ENV: prod
